- name: Import NodeJS common role
  ansible.builtin.include_role:
    name: "{{ app_name }}"
    tasks_from: java.yaml

- name: install MySQL Client
  ansible.builtin.dnf:
    name:
       - mysql
       - python3-mysqlclient
    state: installed

- name: Load Schema
  community.mysql.mysql_db:
    state: import
    name: all
    target: /app/db/{{ item }}.sql
    login_host: mysql-{{ ENV }}.azdevops.online
    login_user: root
    login_password: Roboshop@1
  loop:
    - schema
    - app-user
    - master-data
