- name: Import NodeJS common role
  ansible.builtin.include_role:
    name: "{{ app_name }}"
    tasks_from: java.yaml

- name: install MySQL Client
  ansible.builtin.dnf:
    name:
       - mysql
       - python3-mysqlclient
    state: installed

- name: Load Schema
  community.mysql.mysql_db:
    state: import
    name: all
    target: /app/db/schema.sql
    login_host: mysql-dev.azdevops.online
    login_user: root
    login_password: Roboshop@1


- name: Load App user
  community.mysql.mysql_db:
    state: import
    name: all
    target: /app/db/app-user.sql
    login_host: mysql-dev.azdevops.online
    login_user: root
    login_password: Roboshop@1


- name: Load Master Data
  community.mysql.mysql_db:
    state: import
    name: all
    target: /app/db/master-data.sql
    login_host: mysql-dev.azdevops.online
    login_user: root
    login_password: Roboshop@1


