- name: Import NodeJS common role
  ansible.builtin.include_role:
    name: "{{ app_name }}"
    tasks_from: nodejs.yaml

- name: Copy MongoDB repo file
  ansible.builtin.template:
    src: mongodb.repo
    dest: "/etc/yum.repos.d/{{ app_name }}.repo"

- name: Install MongoDB
  ansible.builtin.dnf:
    name: "{{ app_name }}-org"
    state: installed

- name: Load Master Data
  community.mongodb.mongodb_shell:
    login_host: mongodb-{{ ENV }}.azdevops.online
    file: "</app/db/master-data.js"
    idempotent: yes
