- name: Create Application User
  ansible.builtin.user:
    name: roboshop

- name: Remove Application Directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create Application Directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download app ZIP
  ansible.builtin.get_url:
    url: "https://roboshop-artifacts.s3.amazonaws.com/{{ app_name }}-v3.zip"
    dest: "/tmp/{{ app_name }}-v3.zip"

- name: Extract app content
  ansible.builtin.unarchive:
    src: "/tmp/{{ app_name }}-v3.zip"
    dest: /app
    remote_src: yes





