- name: Setup SystemD service file
  ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service
    mode: '0644'

- name: Reload systemd daemon
  ansible.builtin.command:
    cmd: systemctl daemon-reload

- name: Start and enable catalogue service
  ansible.builtin.systemd:
    name: catalogue
    state: started
    enabled: true

