- name: Setup SystemD service file
  ansible.builtin.copy:
    src: catalogue.service"
    dest: /etc/systemd/system/catalogue.service

- name: Start Application
  ansible.builtin.systemd_service:
    name: catalogue
    state: restarted
    enabled: true
    daemon_reload: true
